### ISSUE TITLE
Fix autopublish of monorepo packages and implement release process

### ISSUE THREAD

**Issue by pete-watters** [leather-io/mono#29]
Since [we have moved ](https://github.com/leather-wallet/mono/pull/12/)to `npm`, auto publish of packages is no longer working. 

The scope of this task involves:
- fixing auto release
- releasing packages automatically with semantic release (not on manual git release)
- adding documentation for how to add new libraries and make sure they auto release

I had investigated using [Nx](https://github.com/leather-wallet/mono/issues/6) and decided against it, but when we added [Expo](https://github.com/leather-wallet/mono/issues/9) we needed to change from `pnpm` to `npm` and this meant the process that was in place stopped working.

**Comment by markmhendrickson** [comment]
Is the current consequence of this being broken at the moment that more manual steps are needed by a developer each time we release?

**Comment by pete-watters** [comment]
Yes it just means if we merge new changes to our packages we now need to run a manual step to publish them to `npm`

It's not a huge overhead to do that right now so it's not too bad but it was working automatically before and it's important to fix that when we start focusing on adding new packages here

**Comment by kyranjamie** [comment]
This is critical to the adoption of mono repo and being productive with it. Moving to dev backlog.
