### ISSUE TITLE
Update Src20CryptoAssetInfo to include tokenImage

### ISSUE THREAD

**Issue by RisingStarDev** [leather-io/mono#724]
![Image](https://github.com/user-attachments/assets/bb389cc0-0e8d-477c-9678-f3b35293bca9)

Hi @leather-io/query developer team,
Thanks for fixing src20 token schema last time.
But I missed one thing last time.
Can you fix stamps-by-address.hooks.ts file again so that it passes newly added deploy_tx & deploy_img props?
Then, I can submit another issue on @leather-io/extension to display correct images for src20 tokens from deploy_img props.
Please fix this issue and release a new version soon.
I would appreciate your help. Thanks.

**Comment by pete-watters** [comment]
Thanks @RisingStarDev , I've added these in [a PR](https://github.com/leather-io/mono/pull/771/commits/b971abbbafb54104f513f15be31c7c795293fcbd) . 

I'll get that release ASAP and then I can help finish off [your PR](https://github.com/leather-io/extension/pull/6009)
