### ISSUE TITLE
Waitlist app: Add delay + confirm 

### ISSUE THREAD

**Issue by fabric-8** [leather-io/mono#97]
Currently, when submitting a valid email address, the state goes straight to the final message which feels a bit abrupt:

<img src="https://github.com/leather-wallet/mono/assets/4112698/be0bc531-81c4-4a1e-b97a-e17a00d334c8" width=50% height=50%>

---

As an improvement, it would be great if we could had a fake load/spinner for about 1200ms, followed by a brief button success state (800ms), before transitioning to the final message:

<img src="https://github.com/leather-wallet/mono/assets/4112698/fa45173c-4ca6-4737-a556-ea4bcd63f35a" width=50% height=50%>

[Respective frames on Figma](https://www.figma.com/file/FlmF7ropcijOb7iVSDqNn0/%F0%9F%9F%A7-Web-App-Explorations-2024-H1?type=design&node-id=5601%3A131019&mode=design&t=4qTrZKivCBh4sig7-1)

**Comment by markmhendrickson** [comment]
@edgarkhanzadian is this issue still relevant?
